### ISSUE TITLE
In Serializers

### ISSUE THREAD

**Issue by dhuddell** [ga-wdi-boston/rails-summative-adv-08#18]
gem "active_model_serializers", github: "rails-api/active_model_serializers"``

--this is the code snippet, looks like the you started it with 1 backtick and ended with 3. Will likely mess a few people up.

Improved:

`gem "active_model_serializers", github: "rails-api/active_model_serializers"`

**Comment by GA-MEB** [comment]
We're changing up how we load the gem. Closing this issue.
